import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { isAdminAuthed } from '@/lib/adminAuth'
import { generateToken } from '@/lib/utils'

export const dynamic = 'force-dynamic'

function getDb() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    {
      global: {
        fetch: (url, options = {}) => fetch(url, { ...options, cache: 'no-store' }),
      },
    }
  )
}

export async function POST(req: NextRequest) {
  if (!isAdminAuthed(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  try {
    const { matric_number } = await req.json()
    if (!matric_number?.trim()) return NextResponse.json({ error: 'Matric number is required' }, { status: 400 })

    const db = getDb()
    const matric = matric_number.toUpperCase().trim()

    const { data: voter } = await db.from('voters').select('*').eq('matric_number', matric).single()
    if (!voter) return NextResponse.json({ error: 'No voter found with that matric number' }, { status: 404 })
    if (voter.has_voted) return NextResponse.json({ error: 'This student has already voted. Token cannot be regenerated.' }, { status: 400 })

    const newToken = generateToken()
    await db.from('voters').update({ token: newToken, token_used: false }).eq('id', voter.id)

    await db.from('audit_log').insert({
      event_type: 'TOKEN_REGENERATED',
      matric_number: matric,
      details: `Token manually regenerated by admin for ${voter.full_name}`,
      success: true,
    })

    return NextResponse.json({
      success: true,
      voter: { full_name: voter.full_name, matric_number: voter.matric_number, phone: voter.phone, token: newToken }
    })
  } catch (err) {
    console.error(err)
    return NextResponse.json({ error: 'Server error' }, { status: 500 })
  }
}